# Generated by Django 4.2.16 on 2024-11-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transbackend', '0003_game_gameroom_rename_userid_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
