# Generated by Django 4.2.16 on 2024-11-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transbackend', '0004_user_is_authenticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
