# Generated by Django 4.2.16 on 2024-11-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transbackend', '0011_alter_user_email_user_unique_email_for_active_users_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_for_active_users',
        ),
    ]
