# Generated by Django 4.2.16 on 2024-11-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transbackend', '0012_remove_user_unique_username_for_active_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
