# Generated by Django 4.2.16 on 2024-11-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transbackend', '0013_alter_user_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_for_active_users',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', False), _negated=True), fields=('email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', False), _negated=True), fields=('username',), name='unique_username'),
        ),
    ]
