# Generated by Django 4.2.16 on 2024-11-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transbackend', '0016_remove_user_unique_email_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
