# Generated by Django 4.2.16 on 2024-11-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transbackend', '0018_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
