# Generated by Django 4.2.16 on 2024-11-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transbackend', '0019_user_is_online_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
