# Generated by Django 4.2.16 on 2024-11-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transbackend', '0020_remove_user_is_active_remove_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameHistory',
        ),
        migrations.DeleteModel(
            name='GameRoom',
        ),
    ]
